services:
  - type: web
    name: pos-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: POS_API_KEY
        value: pos_secret_key
      - key: CRM_API_KEY
        value: mysecretkey
      - key: CRM_BASE_URL
        value: https://crm-n577.onrender.com
      - key: DATABASE_URL
        value: postgresql://demo_db_wmet_user:lfxvuYWFNbZ946wSCwWijJO3OKS2BDSm@dpg-d2113iemcj7s73ea3bgg-a.oregon-postgres.render.com/demo_db_wmet
      - key: POS_JWT_SECRET
        value: pos_jwt_secret_key_change_in_production_12345
      - key: PORT
        value: 8001
      - key: HOST
        value: 0.0.0.0 
